apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    type: amazonEBS
spec:
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-066ab8df25c908ae2"
